import type { Domain, ResourceDef, SectionSegment } from '../schemas/types.js';
import type { Mode } from '../schemas/types.js';

export const DOMAIN_FILES: Record<Domain | 'execute-referencing' | 'design-reference', string> = {
  os: 'WORKFLOW_OS_v1.md',
  freelancing: 'WORKFLOW_FREELANCING_v1.md',
  products: 'WORKFLOW_PRODUCTS_v1.md',
  content: 'WORKFLOW_CONTENT_v1.md',
  execution: 'WORKFLOW_EXECUTION_v1.md',
  investing: 'WORKFLOW_INVESTING_v1.md',
  utility: 'UTILITY_PROMPTS_v1.md',
  'execute-referencing': 'WORKFLOW_EXECUTE_REFERENCING_v1.md',
  'design-reference': 'DESIGN_MD_REFERENCE.md',
};

export const DOMAIN_URI_MAP: Record<Domain, string> = {
  os: 'workflow://os/v1',
  freelancing: 'workflow://freelancing/v1',
  products: 'workflow://products/v1',
  content: 'workflow://content/v1',
  execution: 'workflow://execution/v1',
  investing: 'workflow://investing/v1',
  utility: 'workflow://utility/v1',
};

export const DOMAIN_SEQUENCES: Record<Domain, string[]> = {
  os: ['route', 'diagnose', 'run', 'optimize_once', 'next_action'],
  freelancing: ['skill', 'niche', 'offer', 'pricing', 'portfolio', 'outreach', 'first_client', 'premium', 'growth'],
  products: ['idea', 'validate', 'build', 'value', 'pricing', 'offer', 'first_sale'],
  content: ['audience_pain', 'direction', 'ideas', 'hooks', 'write', 'improve', 'optimize', 'consistency'],
  execution: ['do_now', 'organize', 'simplify', 'unblock', 'sprint', 'priorities', 'momentum'],
  investing: ['analyze', 'watchlist', 'news', 'trade_setup', 'red_flags', 'trade_review', 'system'],
  utility: [
    'clarity_rewrite',
    'conversion_rewrite',
    'tone_calibration',
    'structure_rebuild',
    'audience_rewrite',
    'impact_compressor',
    'blind_spot_finder',
    'shortcut_strategy',
    'ultra_leverage',
    'momentum_amplifier',
  ],
};

export const DOMAIN_STAGE_ALIASES: Record<Domain, Record<string, string>> = {
  os: {
    diagnose: 'diagnose',
    route: 'route',
    run: 'run',
    optimize: 'optimize_once',
    optimize_once: 'optimize_once',
    next: 'next_action',
    next_action: 'next_action',
  },
  freelancing: {
    skill: 'skill',
    niche: 'niche',
    offer: 'offer',
    pricing: 'pricing',
    portfolio: 'portfolio',
    outreach: 'outreach',
    first_client: 'first_client',
    premium: 'premium',
    growth: 'growth',
  },
  products: {
    idea: 'idea',
    validation: 'validate',
    validate: 'validate',
    product_shape: 'build',
    shape: 'build',
    build: 'build',
    value: 'value',
    pricing: 'pricing',
    offer: 'offer',
    first_sale: 'first_sale',
  },
  content: {
    audience: 'audience_pain',
    audience_pain: 'audience_pain',
    direction: 'direction',
    ideas: 'ideas',
    hooks: 'hooks',
    write: 'write',
    improve: 'improve',
    optimize: 'optimize',
    consistency: 'consistency',
  },
  execution: {
    do_now: 'do_now',
    organize: 'organize',
    simplify: 'simplify',
    unblock: 'unblock',
    sprint: 'sprint',
    priorities: 'priorities',
    momentum: 'momentum',
  },
  investing: {
    analyze: 'analyze',
    watchlist: 'watchlist',
    news: 'news',
    trade_setup: 'trade_setup',
    red_flags: 'red_flags',
    trade_review: 'trade_review',
    system: 'system',
  },
  utility: {
    clarify: 'clarity_rewrite',
    clarity_rewrite: 'clarity_rewrite',
    compress: 'impact_compressor',
    impact_compressor: 'impact_compressor',
    restructure: 'structure_rebuild',
    structure_rebuild: 'structure_rebuild',
    optimize: 'ultra_leverage',
    ultra_leverage: 'ultra_leverage',
    adapt: 'audience_rewrite',
    audience_rewrite: 'audience_rewrite',
    blind_spots: 'blind_spot_finder',
    blind_spot_finder: 'blind_spot_finder',
    simplify: 'clarity_rewrite',
    shortcut_strategy: 'shortcut_strategy',
    momentum_amplifier: 'momentum_amplifier',
    conversion_rewrite: 'conversion_rewrite',
    tone_calibration: 'tone_calibration',
  },
};

export const MODE_TO_PROMPT: Record<Mode, string> = {
  clarify: 'clarify_task',
  strategy: 'strategize_task',
  build: 'build_output',
  persuasion: 'improve_persuasion',
  execution: 'force_execution',
  review: 'review_optimize',
};

export const SECTION_SEGMENTS: readonly SectionSegment[] = [
  { key: 'execution/input', heading: '### 3.1 INPUT', titleSuffix: 'Execution Input' },
  { key: 'execution/decision-rule', heading: '### 3.2 DECISION RULE', titleSuffix: 'Execution Decision Rule' },
  { key: 'execution/sequence', heading: '### 3.3 SEQUENCE', titleSuffix: 'Execution Sequence' },
  { key: 'execution/command-format', heading: '### 3.4 COMMAND FORMAT', titleSuffix: 'Execution Command Format' },
  { key: 'execution/operating-rules', heading: '### 3.5 OPERATING RULES', titleSuffix: 'Execution Operating Rules' },
  { key: 'output/response-shape', heading: '### 4.1 RESPONSE SHAPE', titleSuffix: 'Output Response Shape' },
  { key: 'output/output-rules', heading: '### 4.2 OUTPUT RULES', titleSuffix: 'Output Rules' },
  { key: 'output/completion-rule', heading: '### 4.3 COMPLETION RULE', titleSuffix: 'Completion Rule' },
] as const;

export const STATIC_RESOURCES: ResourceDef[] = [
  {
    id: 'workflow-os',
    domain: 'os',
    uri: DOMAIN_URI_MAP.os,
    fileName: DOMAIN_FILES.os,
    title: 'Workflow OS v1',
    description: 'Top-level router, operating modes, and output discipline.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-freelancing',
    domain: 'freelancing',
    uri: DOMAIN_URI_MAP.freelancing,
    fileName: DOMAIN_FILES.freelancing,
    title: 'Workflow Freelancing v1',
    description: 'Freelancing workflow: skill to premium offer.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-products',
    domain: 'products',
    uri: DOMAIN_URI_MAP.products,
    fileName: DOMAIN_FILES.products,
    title: 'Workflow Products v1',
    description: 'Digital product workflow: idea to first sale.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-content',
    domain: 'content',
    uri: DOMAIN_URI_MAP.content,
    fileName: DOMAIN_FILES.content,
    title: 'Workflow Content v1',
    description: 'Content and persuasion workflow.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-execution',
    domain: 'execution',
    uri: DOMAIN_URI_MAP.execution,
    fileName: DOMAIN_FILES.execution,
    title: 'Workflow Execution v1',
    description: 'Execution workflow for anti-overwhelm and momentum.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-investing',
    domain: 'investing',
    uri: DOMAIN_URI_MAP.investing,
    fileName: DOMAIN_FILES.investing,
    title: 'Workflow Investing v1',
    description: 'Investing workflow: analysis to system design.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-utility',
    domain: 'utility',
    uri: DOMAIN_URI_MAP.utility,
    fileName: DOMAIN_FILES.utility,
    title: 'Utility Prompts v1',
    description: 'Supporting utility prompts and optimization tools.',
    mimeType: 'text/markdown',
  },
  {
    id: 'workflow-execute-referencing',
    domain: 'execute-referencing',
    uri: 'workflow://execute-referencing/v1',
    fileName: DOMAIN_FILES['execute-referencing'],
    title: 'Workflow Execute Referencing v1',
    description: 'Dispatcher/orchestration policy for the seven v1 workflow files.',
    mimeType: 'text/markdown',
  },
  {
    id: 'design-md-reference',
    domain: 'design-reference',
    uri: 'workflow://design-reference/v1',
    fileName: DOMAIN_FILES['design-reference'],
    title: 'DESIGN.md Reference',
    description: 'Google DESIGN.md open-source specification reference.',
    mimeType: 'text/markdown',
  },
];
